core/urls.py
from django.urls import path, include
from core import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name="index"),
    path('products/',views.product_list_view,name="product-list"),
    path('categories/',views.category_list_view,name="category-list"),
    path('categories/<cid>/',views.category_product_list_view,name="category-product-list"),
    path('vendors/',views.vendor_list_view,name="vendor-list"),
    path('create-vendor-profile/',views.create_vendor_profile,name="create-vendor-profile"),
    path('vendor-profile/',views.vendor_profile,name="vendor-profile"),
    path('vendors/<vid>',views.vendor_detail_view,name="vendor-detail"),
    path('products/<pid>',views.product_detail_view,name="product-detail"),
    path('products/tag/<slug:tag_slug>/',views.tag_list, name="tag"),
    path('ajax-add-review/<int:pid>/',views.ajax_add_review, name="ajax-add-review"),
    path('search/',views.search_view,name="search"),
    path('filter-product/',views.filter_product,name="filter-product"),
    path('add-to-cart/', views.add_to_cart,name="add-to-cart"),
    path('cart/', views.cart_view,name="cart"),
    path('delete-from-cart/', views.delete_item_from_cart,name="delete-from-cart"),
    path('update-cart/', views.update_from_cart,name="update-cart"),
    path('checkout/', views.checkout_view,name="checkout"),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-completed/', views.payment_completed_view, name="payment-completed"),
    path('payment-failed/', views.payment_failed_view, name="payment-failed"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('order/', views.order, name="order"),
    path('order-detail/<int:id>/', views.order_detail, name="order-detail"),
    path('profile/', views.profile, name="profile"),
    path('address/', views.address, name="address"),
    path('update-address/', views.update_address, name="update-address"),
    path('add-address/', views.add_address, name="add-address"),
    path('update-profile/', views.update_profile, name="update-profile"),
    path('create-profile/', views.create_profile, name="create-profile"),
    path('wishlist/', views.wishlist_view, name="wishlist"),
    path('add-to-wishlist/', views.add_to_wishlist, name="add-to-wishlist"),
    path('remove-from-wishlist/', views.remove_from_wishlist, name="remove-from-wishlist"),
    path('contact/', views.contact_view, name="contact"),
    path('contact-page/', views.contact_ajax, name="contact-page"),
    path('cash-on-delivery/', views.cash_on_delivery_view, name='cash-on-delivery'),
    path('create-store/', views.create_store, name='create-store'),
    path('update-store/', views.update_store, name='update-store'),
    path('store-products/', views.store_products, name='store-products'),
    path('create-products/', views.create_products, name='create-products'),
    path('update-product/<pid>', views.update_product, name='update-product'),
    path('user-notifications/', views.user_notifications, name='user-notifications'),
    path('vendor-notifications/', views.vendor_notifications, name='vendor-notifications'),
    path('vendor-orders/', views.vendor_orders, name='vendor-orders'),
    path('customer-profile/<id>', views.customers_profile, name='customer-profile'),
    path('paypal_pay/', views.paypal_view, name='paypal_pay'),
    path('vendor-dashboard/', views.vendor_dashboard, name='vendor-dashboard'),

   
    
]
    
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shaheerecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path('user/',include("userauths.urls")),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static2/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path, include
from userauths import views
from core.views import create_profile

app_name = 'userauths'

urlpatterns = [
    path("signup", views.register_views, name="signup"),
    path("signin", views.login_view, name="signin"),
    path("signout", views.logout_view, name="signout"),
    path("change_password", views.change_password, name="change_password"),
    path("create-profile/", create_profile, name="create-profile"),
    path("delete-account/", views.delete_account, name="delete-account")
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    email=models.EmailField(unique=True)
    username=models.CharField(max_length=100)
    bio=models.CharField(max_length=255)
    is_vendor = models.BooleanField(null=True, default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username
    

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User


class UserRegistrationForm(UserCreationForm):
    username=forms.CharField(widget=forms.TimeInput(attrs={"placeholder":"Username"}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email"}))
    password1=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}))
    password2=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password"}))

    class Meta:
        model = User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegistrationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from userauths.models import User
from django.contrib.auth.decorators import login_required
# User = settings.AUTH_USER_MODEL

def register_views(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user=form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, Your account was created successfully. Please create your profile")
            new_user= authenticate(username=form.cleaned_data['email'],
                                   password=form.cleaned_data['password1']
            
            )
            login(request, new_user)
            return redirect("create-profile")
    else:
        print("User cannot be registered")
        form = UserRegistrationForm()

    context = {
        'form': form,
    }

    return render(request, "userauths/signup.html", context)

def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey! You are already logged in...")
        return redirect("/")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user=authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in")
                return redirect("/")
            else:
                messages.warning(request, "User does not exist. Please create an account")
        except:
            messages.warning(request, f"User with {email} does not exist")
        
    return render(request, "userauths/signin.html")

def logout_view(request):
    logout(request)
    messages.success(request, "You logged out")
    return redirect("userauths:signin")

from django.contrib.auth.hashers import check_password

@login_required
def change_password(request):
    if request.method == "POST":
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        confirm_password = request.POST.get("confirm_password")
        user = User.objects.get(email=request.user.email)
        if not check_password(old_password, user.password):
            messages.warning(request, "Old password was incorrect")
        elif confirm_password != new_password:
            messages.warning(request, "Passwords do not match")
        else:
            user.set_password(new_password)
            user.save()
            user = authenticate(request, email=user.email, password=new_password)
            login(request, user)
            messages.success(request, "Password changed successfully")
            return redirect("/")
    return render(request, "userauths/change_password.html")


@login_required
def delete_account(request):
    if request.method == "POST":
        request.user.delete()
        logout(request)
        messages.success(request, "Account Deleted Successfully!")
        return redirect("/")

    return render(request, "userauths/delete-account.html")

templates/userauths/change_password.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
<!-- <form method="post" action="" >
    {% csrf_token %}
    {{form.as_p}}
<button type="submit">Register</button>
</form> -->

{% block title %}
Change Password
{% endblock title %}
{% block body %}
{% load static %}

<!--page Header-->
<section class="page-header parallaxie padding_top center-block">
   <div class="container">
      <div class="row">
         <div class="col-sm-12">
            <div class="page-titles text-center">
               <h2 class="whitecolor font-light bottom30">Change Password</h2>
               <ul class="breadcrumb justify-content-center">
                  <li class="breadcrumb-item"><a href="/">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Change Password</li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</section>
<!--page Header ends-->


<!-- Login Register -->
<section id="our-blog" class="padding text-center">
   <div class="container">
      <div class="row d-flex justify-content-center">
         <div class="col-lg-4 col-md-6 col-sm-10">
            <div class="bglight logincontainer">
               <h3 class="darkcolor bottom35">Change Your Password</h3>


               <form method="post" class="getin_form border-form" id="login">
                  {% csrf_token %}
                  <div class="row">
                     <div class="col-md-12 col-sm-12">
                        <div class="form-group bottom35">
                           <input class="form-control" name="old_password" type="password" placeholder="Old Password:"
                              required>
                        </div>
                     </div>
                     <div class="col-md-12 col-sm-12">
                        <div class="form-group bottom35">
                           <input class="form-control" name="new_password" type="password" placeholder="New Password:"
                              required>
                        </div>
                     </div>
                     <div class="col-md-12 col-sm-12">
                        <div class="form-group bottom35">
                           <input class="form-control" name="confirm_password" type="password"
                              placeholder="Confirm Password:" required>
                        </div>
                     </div>
                     <div class="col-md-12 col-sm-12">
                        <div class="form-group bottom35">



                        </div>
                     </div>
                     <div class="col-sm-12">
                        <button type="submit" class="button btnprimary">Change Password</button>

                     </div>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</section>
<!--Login Ends-->
{% endblock body %}

templates/userauths/delete-account.html
{% extends 'core/base.html' %}
{% block title %}
Payment Failed
{% endblock title %}

{% block body %}
{% load static %}
<main id="cart-list">
   <!--page Header-->
   <section class="page-header parallaxie padding_top center-block">
      <div class="container">
         <div class="row">
            <div class="col-sm-12">
               <div class="page-titles text-center">
                  <h2 class="whitecolor font-light bottom30">Delete Account</h2>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!--Error 404 SECTION-->
   <section id="error" class="padding">
      <div class="container">
         <div class="row">
            <div class="col-md-3 col-sm-2"></div>
            <div class="col-md-6 col-sm-8 text-center">
               <div class="error wow zoomIn">
                  <h1>Delete</h1>
                  <h2>Account</h2>
               </div>
               <p class="heading_space">Deleting the account will also delete the store and all your data. <span
                     style="color: red; font-weight: 600;">Are you sure</span> ?</p>
                     <form method="post">
                        {% csrf_token %}
                         <button class="button btnprimary btn-gradient-hvr wow fadeInLeft" type="submit" style="background: red;">Yes, Delete my Account</button>
                        </form>
                        </div>
            <div class="col-md-3 col-sm-2"></div>
         </div>
      </div>
   </section>
   {% endblock body %}

templates/userauths/signin.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
<!-- <form method="post" action="" >
    {% csrf_token %}
    {{form.as_p}}
<button type="submit">Register</button>
</form> -->

{% block title %}
Login
{% endblock title %}
{% block body %}
{% load static %}

<!--page Header-->
<section class="page-header parallaxie padding_top center-block">
   <div class="container">
      <div class="row">
         <div class="col-sm-12">
            <div class="page-titles text-center">
               <h2 class="whitecolor font-light bottom30">Login</h2>
               <ul class="breadcrumb justify-content-center">
                  <li class="breadcrumb-item"><a href="/">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Login</li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</section>
<!--page Header ends-->


<!-- Login Register -->
<section id="our-blog" class="padding text-center">
   <div class="container">
      <div class="row d-flex justify-content-center">
         <div class="col-lg-4 col-md-6 col-sm-10">
            <div class="bglight logincontainer">
               <h3 class="darkcolor bottom35">Login </h3>


               <form method="post" class="getin_form border-form" id="login">
                  {% csrf_token %}
                  <div class="row">
                     <div class="col-md-12 col-sm-12">
                        <div class="form-group bottom35">
                           <input class="form-control" name="email" type="email" placeholder="Email:" required>
                        </div>
                     </div>
            
                        <div class="col-md-12 col-sm-12">
                           <div class="form-group bottom35">
                              <input class="form-control" name="password" type="password" id="password-field" placeholder="Password:" required >
                           </div>
                           <input  id="password-toggle" type="checkbox" style="margin-right: 5px;"><label class="form-check-label" for="rememberMe">
                               See Password
                           </label>
                        </div>
            
                     <div class="col-md-12 col-sm-12">
                        <div class="form-group bottom35">

                          

                        </div>
                     </div>
                     <div class="col-sm-12">
                        <button type="submit" class="button btnprimary">Login</button>
                        <p class="top20 log-meta"> Don't have an account? <a href="{% url 'userauths:signup' %}">Sign Up
                              Now</a> </p>
                     </div>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</section>
<script>
   const passwordField = document.getElementById("password-field");
const passwordToggle = document.getElementById("password-toggle");
passwordToggle.addEventListener("click", function () {
  if (passwordField.type === "password") {
    passwordField.type = "text";
    
  } else {
    passwordField.type = "password";
   
  }
});

</script>
<!--Login Ends-->
{% endblock body %}

templates/userauths/signup.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
<!-- <form method="post" action="" >
    {% csrf_token %}
    {{form.as_p}}
<button type="submit">Register</button>
</form> -->

{% block title %}
Signup
{% endblock title %}
{% block body %}
{% load static %}

<!--page Header-->
<section class="page-header parallaxie padding_top center-block">
   <div class="container">
      <div class="row">
         <div class="col-sm-12">
            <div class="page-titles text-center">
               <h2 class="whitecolor font-light bottom30">Register</h2>
               <ul class="breadcrumb justify-content-center">
                  <li class="breadcrumb-item"><a href="/">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Login</li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</section>
<!--page Header ends-->


<!-- Login Register -->
<section id="our-blog" class="padding text-center">
   <div class="container">
      <div class="row d-flex justify-content-center">
         <div class="col-lg-4 col-md-6 col-sm-10">
            <div class="bglight logincontainer">
               <h3 class="darkcolor bottom35">Create Your account </h3>
               {% if form.errors %}
               <div class="alert alert-danger">
                  <strong>{{form.errors}}</strong>

               </div>
               {% endif %}

               <form method="post" class="getin_form border-form" id="login">
                  {% csrf_token %}
                  <div class="row">

                     <div class="col-md-12 col-sm-12">
                        <div class="form-group bottom35">
                           {{form.username|attr:"class:form-control"}}
                        </div>
                     </div>
                     <div class="col-md-12 col-sm-12">
                        <div class="form-group bottom35">
                           {{form.email|attr:"class:form-control"}}
                        </div>
                        <div style="font-size: smaller;" class="help-block">
                           <spam style="color: #00bcd4">Note: </spam>Will also be used for emails
                        </div>
                     </div>
                  </div>
                  <div class="col-md-12 col-sm-12">
                     <div class="form-group bottom35">
                        {{form.password1|attr:"class:form-control"}}
                     </div>
                  </div>
                  <br>
                  <div class="col-md-12 col-sm-12">
                     <div class="form-group bottom35">
                        {{form.password2|attr:"class:form-control"}}
                     </div>
                  </div>
                  <!-- <div class="col-md-12 col-sm-12">
                         <div class="form-group bottom35">
                            <input class="form-control" type="password" placeholder="Confirm Password:" required>
                         </div>
                      </div> -->
                  <br>
                  <div class="col-sm-12">
                     <button type="submit" style="width: 50%; display: block; margin: 0 auto;"
                        class="button btnprimary">Login</button>
                     <p class="top20 log-meta"> Already have an account? <a href="{% url 'userauths:signin' %}">Sign
                           In</a> </p>
                  </div>
            </div>
            </form>
         </div>
      </div>
   </div>
   </div>
</section>
<!--Login Ends-->
{% endblock body %}